// src/components/sections/Features.jsx (From previous response, adapted slightly)
import React from 'react';
import ResponsiveImage from '../common/ResponsiveImage';
import SectionWrapper from '../common/SectionWrapper';

const Features = () => {
  return (
      <SectionWrapper id="features" className="bg-white">
            <div className="flex flex-col lg:flex-row items-center justify-between gap-8">
                    <div className="lg:w-1/2">
                              <h2 className="text-3xl font-bold text-neutral-dark mb-4">Why Choose BeeHive Essentials</h2>
                                        <p className="text-lg text-neutral-dark mb-6">We provide top-quality beekeeping supplies and education to help you build a thriving apiary. Our products are designed for sustainability, ease of use, and maximum honey production.</p>
                                                  <ul className="space-y-4">
                                                              <li className="flex items-start">
                                                                            <span className="bg-accent text-white rounded-full w-8 h-8 flex items-center justify-center mr-4 font-bold">1</span>
                                                                                          <div>
                                                                                                          <h3 className="text-xl font-semibold text-neutral-dark">Quality Hives & Equipment</h3>
                                                                                                                          <p className="text-neutral-dark">Durable, eco-friendly beehives sourced from sustainable materials to ensure long-lasting performance.</p>
                                                                                                                                        </div>
                                                                                                                                                    </li>
                                                                                                                                                                <li className="flex items-start">
                                                                                                                                                                              <span className="bg-accent text-white rounded-full w-8 h-8 flex items-center justify-center mr-4 font-bold">2</span>
                                                                                                                                                                                            <div>
                                                                                                                                                                                                            <h3 className="text-xl font-semibold text-neutral-dark">Expert Guidance</h3>
                                                                                                                                                                                                                            <p className="text-neutral-dark">Comprehensive resources and tutorials for beginners and pros to master beekeeping techniques.</p>
                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                  <li className="flex items-start">
                                                                                                                                                                                                                                                                                <span className="bg-accent text-white rounded-full w-8 h-8 flex items-center justify-center mr-4 font-bold">3</span>
                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                              <h3 className="text-xl font-semibold text-neutral-dark">Sustainable Practices</h3>
                                                                                                                                                                                                                                                                                                                              <p className="text-neutral-dark">Promoting bee health and environmental conservation with organic methods and pollinator-friendly products.</p>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                  <div className="lg:w-1/2">
                                                                                                                                                                                                                                                                                                                                                                                            <ResponsiveImage
                                                                                                                                                                                                                                                                                                                                                                                                        src="/assets/images/beehive-setup.jpg"
                                                                                                                                                                                                                                                                                                                                                                                                                    alt="Beekeeper working with sustainable hives in a natural setting"
                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full h-auto rounded-lg shadow-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </SectionWrapper>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Features;